### ISSUE TITLE
Setup the project

### ISSUE THREAD

**Issue by sergey-shandar** [sergey-shandar/purelogic-ts#1]

**Comment by alaudo** [comment]
## Steps to set-up a proper IDE:
1. Download and install Visual Studio Code from [here](https://code.visualstudio.com/Download)
2. Download and install the latest stable version of TypeScript from [here](https://www.typescriptlang.org/#download-links)
3. Download and install Node.JS from [here](https://nodejs.org/en/download/)
4. What to do next?

**Comment by sergey-shandar** [comment]
`npm install typescript -g` - this will install the latest version of TypeScript globally.

**Comment by sergey-shandar** [comment]
Sorry, it should be in different order:
1. Download and install Visual Studio Code (this should be optional, some developers prefer other IDE/editors).
2. Download and install Node.JS.
3. Download and install the latest stable version of TypeScript  `npm install typescript -g`
